### PR TITLE
Add macOS and Linux aarch64 and ppc64le builds

### LINKED ISSUE #2: Add macOS and Linux aarch64 and ppc64le builds
It would be good to add macOS builds (both x86 and aarch64) as well as Linux aarch64 and ppc64le builds to the feedstock.

@Kwaizer maybe you can take a look at this (doing something similar to https://github.com/conda-forge/hepmc2-feedstock/issues/8). It might require changes to the packaging system, but we'll find out.

### PR DESCRIPTION
**Pull request by Kwaizer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Resolves #2

### CODE REVIEW

**Review by matthewfeickert — CHANGES_REQUESTED** [review]
@Kwaizer In the PR checklist you need to do

>  Bumped the build number (if the version is unchanged)

and you should step through and check off the other ones (make them `[x]`) before a reviewer is asked to go through this.

You should also add

```
Resolves #2 
```

to the PR body so that it automatically closes out the Issue when merged.

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Comment by matthewfeickert** [comment]
@conda-forge/pyhepmc This PR is ready for review. Please let @Kwaizer know if you have any questions.

**Comment by matthewfeickert** [comment]
@conda-forge/pyhepmc Ping on the review of this.

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Review by cvazquezs — APPROVED** [review]

**Pull request merged**
